#!/bin/sh
[ -z "$ANDROID_NDK" ] && echo "Need to set ANDROID_NDK" && exit 1;

if [ "$#" -ne 1 ] || [ "$1" == "-h" ]; then
    echo "Usage: `basename $0` [armeabi-v7a | arm64-v8a]"
    exit
fi

pushd src/swappy
  rm -rf cmake_$1
  mkdir cmake_$1
  pushd cmake_$1
    cmake \
      -DCMAKE_BUILD_TYPE=Release \
      -DANDROID_PLATFORM=android-26 \
      -DANDROID_NDK=$ANDROID_NDK \
      -DANDROID_STL=c++_static \
      -DANDROID_ABI=$1 \
      -DCMAKE_CXX_FLAGS= \
      -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=./build -B./cmake -H./ ..

    make
    mv libswappy_static.a ./build
  popd
popd
